"""Exomizer protocol (-P) bit flags and defaults.

Mirrors src/flags.h from the reference exomizer distribution.
"""

PBIT_BITS_ORDER_BE = 0
PBIT_BITS_COPY_GT_7 = 1
PBIT_IMPL_1LITERAL = 2
PBIT_BITS_ALIGN_START = 3
PBIT_4_OFFSET_TABLES = 4
PBIT_REUSE_OFFSET = 5

PFLAG_BITS_ORDER_BE = 1 << PBIT_BITS_ORDER_BE
PFLAG_BITS_COPY_GT_7 = 1 << PBIT_BITS_COPY_GT_7
PFLAG_IMPL_1LITERAL = 1 << PBIT_IMPL_1LITERAL
PFLAG_BITS_ALIGN_START = 1 << PBIT_BITS_ALIGN_START
PFLAG_4_OFFSET_TABLES = 1 << PBIT_4_OFFSET_TABLES
PFLAG_REUSE_OFFSET = 1 << PBIT_REUSE_OFFSET

# The default -P39 setting of the raw command.
PROTO_DEFAULT = (
    PFLAG_BITS_ORDER_BE
    | PFLAG_BITS_COPY_GT_7
    | PFLAG_IMPL_1LITERAL
    | PFLAG_REUSE_OFFSET
)

MAX_OFFSET = 65535
